### PR TITLE
Mongo alias

### PR DESCRIPTION
**Pull request by gianiaz**
Adds ability to autowire the default connection

### CODE REVIEW

**Comment by Algatux** [comment]
@gianiaz that service declaration will never work as is. It must be defined inside the client registry.
I have some doubts that what you want to do can be really helpful with mongodb except for the autowire functionality. 
IMHO will be better to have a specialized service with the right connection inside and than autowire that one.

**Comment by Jean85** [comment]
@Algatux the point of this PR is the autowire... 

If you have just one connection (99% of cases, I think) this will make every service work out of the box if you use it.

Also, having it defined in the XML or in the extension it's the same, it's just aliasing the default connection to the FQCN.

**Comment by Algatux** [comment]
> @Algatux the point of this PR is the autowire...
> 
> If you have just one connection (99% of cases, I think) this will make every service work out of the box if you use it.
> 
> Also, having it defined in the XML or in the extension it's the same, it's just aliasing the default connection to the FQCN.

@Jean85 @gianiaz I was referring to the first commit where the alias was the inverse. 

With mongodb, I think, it is more likely that there will be a replicaset (for reliable projects), so I said "will be better" because imho using the autowire directly on the default connection will not be too much useful.
If your problem is the autowire on a single connection, I think you can define an alias in the project while we take a decision on this "problem".

**Comment by Jean85** [comment]
Sure, we're already doing it in our project. We were just thinking that, by default, the autowire should work providing the default connection. In this way, you would just override the autowire only when the default connection is not the right one (which should be a minority of cases).

**Comment by ilario-pierbattista** [comment]
Thank you for your pr @gianiaz, I'm really sorry for being so late.

I must say I actually agree with @Algatux: that should be a project level configuration.
I'm a bit scared putting with kind of implicity into the bundle.

Am I missing something?

**Comment by Jean85** [comment]
Well, that would just be the suggested default and it still can be overridden at will by the project. I just think that 99% of the time that's what is needed.

**Pull request closed without merging**
