### PR TITLE
Allow php 8

### PR DESCRIPTION
**Pull request by Jean85**
Last split from #104.

[EDIT] I had to change a couple of constructors, but luckily the classes were declared `@internal`.

### CODE REVIEW

**Comment by Jean85** [comment]
I had to rollback allowing PHPUnit 9 because it contains a deprecation for Prophecy, which can be fixed using `phpspec/prophecy-phpunit`, but unfortunately it doesn't allow PHP 7.2: https://packagist.org/packages/phpspec/prophecy-phpunit#v2.0.1

**Comment by Jean85** [comment]
Incident in progress for GitHub Actions: https://www.githubstatus.com/incidents/xn0sd2x4nd7f :man_facepalming: I'm lucky today

**Review by ilario-pierbattista — CHANGES_REQUESTED** [review]
There is no reason for keeping those default values.
Having them placed before a required parameters make them required too, hence we can safely drop them.

@Jean85 take a look at #115

**Comment by Jean85** [comment]
Will resolve conflicts by tomorrow :+1:

**Review by ilario-pierbattista — APPROVED** [review]

**Comment by ilario-pierbattista** [comment]
Thank you @Jean85!

**Pull request merged**
