### PR TITLE
Removing fallback logic about authSource

### PR DESCRIPTION
**Pull request by ilario-pierbattista**
#96 complains about some fallback logic about authSource filling. 

This PR aims to make authSource config straightforward and predictable removing the fallback logic introduced in previous version of this bundle.

### CODE REVIEW

**Comment by starred-gijs** [comment]
@ilario-pierbattista Thank for you looking into this, and yes, I can confirm I can now connect without username/password. Also this change does not break my authenticated connection 👍

**Comment by ilario-pierbattista** [comment]
Fine! Use this specific commit hash until the next release

**Comment by starred-gijs** [comment]
Hi, do you plan to release this change?

**Comment by starred-gijs** [comment]
Hmzzz I tried to fork and release a private patch version, but that did not allow it with Symfony 5. The composer requirements were downgraded? Oke I figure something out, no rush for any release!

**Comment by ilario-pierbattista** [comment]
@starred-gijs we still have to add Symfony 5 compatibility. It will be done in the next releases

**Pull request merged**
