### PR TITLE
Use FQCN for controller

### PR DESCRIPTION
**Pull request by starred-gijs**
Needed for Symfony 5.0+, https://github.com/symfony/symfony/blob/5.x/UPGRADE-5.0.md#frameworkbundle

Im not sure what this will to do for Backwards Compatibility?

### CODE REVIEW

**Comment by Jean85** [comment]
IIRC 3.4 is compatible with that naming scheme...

Build is broken though.

**Comment by starred-gijs** [comment]
> IIRC 3.4 is compatible with that naming scheme...

Thanks for checking!

> Build is broken though.

Some oauth github token issue, seems unrelated to this change

**Comment by ilario-pierbattista** [comment]
@starred-gijs #99 should fix build problems. Could you rebase this branch wrt master?

**Comment by starred-gijs** [comment]
Closed in favor of #100

**Pull request closed without merging**
